spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/shopping_cart
    username: shopping
    password: shopping123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true