services:
  postgres:
    image: postgres:15
    container_name: analyzer_postgres
    environment:
      POSTGRES_DB: analyzer
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "6432:5432"