server:
  port: 8080

kafka:
  bootstrap_server: kafka:29092
  topics:
    sensor_events_topic: telemetry.sensors.v1
    hub_events_topic: telemetry.hubs.v1
  key_serialize_class: org.apache.kafka.common.serialization.StringSerializer
  value_serialize_class: io.confluent.kafka.serializers.KafkaAvroSerializer

logging:
  level:
    org:
      zalando:
        logbook: DEBUG
      springframework:
        web: DEBUG