spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6432/analyzer
    username: user
    password: password

grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

kafka:
  hub:
    properties:
      bootstrap.servers: localhost:9092
      client.id: hubConsumer
      group.id: hub-analyzer
      key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value.deserializer: deserializer.HubEventAvroDeserializer
  snapshot:
    properties:
      bootstrap.servers: localhost:9092
      client.id: sensorConsumer
      group.id: sensor-analyzer
      key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value.deserializer: deserializer.SensorsSnapshotAvroDeserializer
  topics:
    hubs-events: telemetry.hubs.v1
    snapshots-events: telemetry.snapshots.v1